Update `bin/release`
KissKissBankBank/kitten pull request #2167
Opened 2020-08-28 05:23 UTC by Morgan-jarry

- Permet de lancer `bin/release` sans avoir à taper le numéro de version
- Met à jour le `README.md`
  - sur la commande `bin/release`
  - inclus le lien de l'app slack pour rediriger directement sur le channel `#kit-ui`

2020-08-28 05:25 UTC, Morgan-jarry commented on bin/release
> +PACKAGE_VERSION=$(cat package.json \
Il s'agit du même code récupérant la version dans le `bin/publish`

2020-08-28 05:25 UTC, Morgan-jarry commented on bin/release
> +echo "You're about to release the next version of kitten $PACKAGE_VERSION"
Pour comprendre la différence entre `$var` et `${var}` [voir ce commentaire sur StackOverflow](https://stackoverflow.com/a/48537621/1149166).

2020-08-28 05:30 UTC, Morgan-jarry commented on bin/release
> +PACKAGE_VERSION=$(cat package.json \
Pour tester en cas de doute :
```sh
PACKAGE_VERSION=$(cat package.json \
  | grep version \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[",]//g' \
  | tr -d '[[:space:]]')
echo $PACKAGE_VERSION
```

2020-08-28 08:06 UTC, joachimesque approved these changes
Bonne idée ! est-ce que ça ne serait pas aussi une bonne occasion pour régler le souci de CI au déploiement ? Je reçois à chaque `bin/publish` un mail de CircleCI pour cette erreur sur la branche `gh-pages` https://app.circleci.com/pipelines/github/KissKissBankBank/kitten/891/workflows/719dfb38-4440-49d3-8143-c952d3b8362d/jobs/6047

2020-08-28 08:06 UTC, joachimesque commented on bin/publish
> +echo "I can use it already with npm install @kisskissbankbank/kitten"
```suggestion
echo "Use it now with npm install @kisskissbankbank/kitten"
```

Already sous-entend un "déjà" qui date d'avant l'action, alors que "now" c'est "on peut maintenant l'utiliser"

2020-08-28 08:08 UTC, LanF3usT approved these changes

2020-08-28 08:25 UTC, FlorentD commented
Je ne comprends pas, quelle version est prise du coup quand tu releases ?

2020-08-28 08:26 UTC, FlorentD requested changes
Je ne comprends pas, quelle version est prise du coup quand tu releases ?

2020-08-28 08:42 UTC, Morgan-jarry commented
> Je ne comprends pas, quelle version est prise du coup quand tu releases ?

@FlorentD Si tu suis le wiki :
https://github.com/KissKissBankBank/kitten#prepare-the-release-pull-request
La version que tu as mis dans le `package.json `

2020-08-28 08:45 UTC, FlorentD commented
Hummm pour moi ce serait le wiki à mettre à jour alors, je trouve que pouvoir utiliser les commandes `patch|minor|major` au moment de la release est plus simple pour faire du `semver` !

2021-05-28 08:19 UTC, FlorentD commented
Cette PR me semble obsolète, je close.
Si quelqu'un veut remettre le sujet sur la table, qu'il n'hésite pas à la ré-ouvrir

2021-05-28 08:19 UTC, closed without merging